# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dd3HIpXI0HKV5PBAi7GXaP0PCZCZsmq2
"""

import pandas as pd

df=pd.read_csv("assignment data.csv")

df.head()

# Convert 'price' and 'sq__ft' columns to numeric
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['sq__ft'] = pd.to_numeric(df['sq__ft'], errors='coerce')

# Calculate the average price per square feet
average_price_per_foot = df['price'].mean() / df['sq__ft'].mean()

# Filter properties sold for less than the average price per feet
filtered_df = df[df['price'] / df['sq__ft'] < average_price_per_foot]

# Write the filtered data to a new CSV file
filtered_df.to_csv('filtered-sales-data.csv', index=False)

# Display the first few rows of the filtered data
print(filtered_df.head())

len(df),len(filtered_df)

